"""Check coursework packages for internal traces and common release defects.

Uses Python's standard library. pypdf is required for PDF text/metadata checks.
Visual inspection and native application verification remain separate checks.
"""
from pathlib import Path,PurePosixPath
from zipfile import ZipFile
import argparse,io,re,sys,xml.etree.ElementTree as ET
ROOT=Path(__file__).resolve().parents[1]
BANNED=re.compile(r'(?i)(?:/Users/|/home/|file://|ClassMic_Submission|\.submission_build|\.c1_build|AGENTS\.md|README\.md|START_HERE|Evidence_and_Confirmations|\brepository\b|\brepo\b|supplied by the user|AI[- ]assisted|generated by (?:AI|ChatGPT|Codex)|as an AI|TO_COMPLETE|READ_BEFORE_UPLOAD|full criteria appear in|revised (?:A2|B2|C1) (?:document|charter)|source: revised|before submission|before upload|Walnut Exporter|Converted Presentation|classroom friction|bounded learning project|A bounded comparison|No test outcomes are asserted|Scheduled dates do not assert actual completion)')
BAD_MEMBER=re.compile(r'(?i)(?:^|/)(?:docs|archive|working|scripts|node_modules|__MACOSX|\.git)(?:/|$)|(?:README|AGENTS|START_HERE|manifest|validation|checklist)|\.(?:md|py|mjs|log)$')
issues=[];counts={};pdf_available=True
try:from pypdf import PdfReader
except ImportError:pdf_available=False

def flag(where,reason):issues.append(f'{where}: {reason}')
def scan(where,data,suffix):
    counts[suffix]=counts.get(suffix,0)+1
    if suffix in {'.docx','.pptx'}:
        with ZipFile(io.BytesIO(data)) as z:
            if z.testzip():flag(where,'corrupt Office package')
            slide_count=0
            for n in z.namelist():
                if re.fullmatch(r'ppt/slides/slide\d+\.xml',n):slide_count+=1
                if 'comments' in n.lower() and n.endswith('.xml'):flag(where,'review comments included')
                if not n.endswith(('.xml','.rels')):continue
                raw=z.read(n)
                try:r=ET.fromstring(raw)
                except ET.ParseError:flag(where,f'invalid XML in {n}');continue
                text=' '.join(r.itertext())
                hit=BANNED.search(text)
                if hit:flag(where,f'internal text in {n}: {hit.group(0)}')
                if n.endswith('.rels'):
                    for rel in r:
                        target=rel.attrib.get('Target','')
                        if rel.attrib.get('TargetMode')=='External' and (target.startswith('file:') or BANNED.search(target)):flag(where,f'internal/external file relationship in {n}')
                if n=='word/document.xml':
                    tags={x.tag.rsplit('}',1)[-1] for x in r.iter()}
                    if tags & {'ins','del','commentRangeStart'}:flag(where,'tracked changes or comment anchors included')
            if any(n.startswith('docProps/thumbnail.') for n in z.namelist()):flag(where,'stale template preview retained')
            if suffix=='.pptx' and slide_count!=3:flag(where,f'expected 3 slides, found {slide_count}')
    elif suffix=='.pdf' and pdf_available:
        r=PdfReader(io.BytesIO(data));text='\n'.join(p.extract_text() or '' for p in r.pages)+' '+str(r.metadata)
        hit=BANNED.search(text)
        if hit:flag(where,'internal PDF content: '+hit.group(0))
        expected=2 if ('Aspiration' in where or 'Charter' in where or 'WBS_and_Schedule' in where) else 4 if 'Business_Case' in where else None
        if expected and len(r.pages)!=expected:flag(where,f'expected {expected} pages, found {len(r.pages)}')
    elif suffix=='.mpp':
        if not data.startswith(bytes.fromhex('d0cf11e0a1b11ae1')):flag(where,'invalid MPP container header')
        for name in ['ClassMic','Temiko Machavariani','Nurtore Arynuruly']:
            if name.encode('utf-16-le') not in data and name.encode() not in data:flag(where,'required project or team identity missing: '+name)
        for marker in ['/Users/','/home/','AI-assisted','ChatGPT','Codex','ClassMic_Submission','Scheduled dates do not assert actual completion']:
            if marker.encode('utf-16-le') in data or marker.encode() in data:flag(where,'internal MPP content: '+marker)
    elif suffix in {'.xml','.csv','.txt'}:
        hit=BANNED.search(data.decode('utf-8'))
        if hit:flag(where,'internal text: '+hit.group(0))
    elif suffix=='.zip':
        with ZipFile(io.BytesIO(data)) as z:
            if z.testzip():flag(where,'corrupt ZIP')
            if len(z.namelist())!=len(set(z.namelist())):flag(where,'duplicate ZIP names')
            for n in z.namelist():
                if n.endswith('/'):continue
                if PurePosixPath(n).is_absolute() or '..' in PurePosixPath(n).parts or BAD_MEMBER.search(n):flag(where,f'non-coursework ZIP member {n}')
                scan(where+'!'+n,z.read(n),Path(n).suffix.lower())
parser=argparse.ArgumentParser()
parser.add_argument('--path',type=Path,default=ROOT/'submissions')
target=parser.parse_args().path.resolve()
if not target.exists():raise FileNotFoundError(target)
files=[target] if target.is_file() else sorted(target.rglob('*'))
if not any(p.is_file() for p in files):raise ValueError('No submission files found')
for p in files:
    if p.is_file():
        rel=str(p.relative_to(ROOT)) if p.is_relative_to(ROOT) else str(p)
        if p.suffix.lower() not in {'.docx','.pptx','.pdf','.xml','.csv','.mpp','.png','.zip'}:flag(rel,'unexpected release file type')
        scan(rel,p.read_bytes(),p.suffix.lower())
print('Checked release files:',counts)
if not pdf_available:flag('environment','pypdf is required to validate PDF text and metadata; use the documented authoring environment')
if issues:
    print('\n'.join(issues));sys.exit(1)
print('PASS: no flagged internal traces, package defects, review comments or page/slide-count mismatches.')
